{{- if not .Values.sysdig.existingAccessKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sysdig.fullname" . }}
  labels:
{{ include "sysdig.labels" . | indent 4 }}
type: Opaque
data:
 access-key : {{ include "helper-lib.accessKey" . | b64enc | quote }}
{{- end }}
