global:
  clusterConfig:
    name: cluster-name
    namespace: sysdig
  sysdig:
    apiKey: aaaa-bbbb-cccc-dddd
    collectorEndpoint: collector.sysdig-cloud.svc.cluster.local
  image:
    registry: quay.io
    tag: latest

sysdigAgent:
  sysdig:
    accessKey: eeee-ffff-gggg-hhhh

nodeAnalyzer:
  nodeAnalyzer:
    apiEndpoint: http://adsfasdfa
